### ISSUE TITLE
[Feat]: 재난상황(in 커뮤니티) API

### ISSUE THREAD

**Issue by nohy6630** [Kusitms-NumberOne/Backend#55]
**Issue**
- 이슈 내용: 재난상황(in 커뮤니티) API

**Branch Name**
- 생성 브랜치 이름 : `feat/situation`

**To-Do List**
- [x] 기존 재난 데이터 이용하여 재난 상황 API 개발
- [x] 각 재난상황에 대한 대화 API 개발 (재난 상황 API와 합쳐서 한번에 반환하는게 좋을듯)

**Comment by versatile0010** [comment]
이거 저 커뮤니티 api 에서 사용한 로직 뭔가 재활용할 수 잇을 듯 해서
후순위로 고고 하시죠!
